name = Push Menu
description = A responsive layout with a multi-level menu pushed in from the left.
preview = preview.png
template = push-menu-layout

; Regions
regions[header]         = Header
regions[navigation]     = Navigation
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/push-menu/push-menu.layout.css

; Scripts
; scripts[] = layouts/push-menu/assets/push-menu.js
scripts[] = js/modernizr.custom.js
