name = DD-Design Primary
description = This is the layout used by a majority of the DD-Design website pages.
preview = preview.png
template = dd-design-primary-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[gallery]        = Header Gallery
regions[feature_first]  = First Feature
regions[feature_second] = Second Feature
regions[feature_third]  = Third Feature
regions[feature_forth]  = Forth Feature
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/dd-design-primary/dd-design-primary.layout.css
stylesheets[all][] = css/layouts/dd-design-primary/dd-design-primary.layout.no-query.css
